require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AwardsController do

  def mock_award(stubs={})
    @mock_award ||= mock_model(Award, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all awards as @awards" do
      Award.stub(:all) { [mock_award] }
      get :index
      assigns(:awards).should eq([mock_award])
    end
  end

  describe "GET show" do
    it "assigns the requested award as @award" do
      Award.stub(:find).with("37") { mock_award }
      get :show, :id => "37"
      assigns(:award).should be(mock_award)
    end
  end

  describe "GET new" do
    it "assigns a new award as @award" do
      Award.stub(:new) { mock_award }
      get :new
      assigns(:award).should be(mock_award)
    end
  end

  describe "GET edit" do
    it "assigns the requested award as @award" do
      Award.stub(:find).with("37") { mock_award }
      get :edit, :id => "37"
      assigns(:award).should be(mock_award)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created award as @award" do
        Award.stub(:new).with({'these' => 'params'}) { mock_award(:save => true) }
        post :create, :award => {'these' => 'params'}
        assigns(:award).should be(mock_award)
      end

      it "redirects to the created award" do
        Award.stub(:new) { mock_award(:save => true) }
        post :create, :award => {}
        response.should redirect_to(award_url(mock_award))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved award as @award" do
        Award.stub(:new).with({'these' => 'params'}) { mock_award(:save => false) }
        post :create, :award => {'these' => 'params'}
        assigns(:award).should be(mock_award)
      end

      it "re-renders the 'new' template" do
        Award.stub(:new) { mock_award(:save => false) }
        post :create, :award => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested award" do
        Award.stub(:find).with("37") { mock_award }
        mock_award.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :award => {'these' => 'params'}
      end

      it "assigns the requested award as @award" do
        Award.stub(:find) { mock_award(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:award).should be(mock_award)
      end

      it "redirects to the award" do
        Award.stub(:find) { mock_award(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(award_url(mock_award))
      end
    end

    describe "with invalid params" do
      it "assigns the award as @award" do
        Award.stub(:find) { mock_award(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:award).should be(mock_award)
      end

      it "re-renders the 'edit' template" do
        Award.stub(:find) { mock_award(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested award" do
      Award.stub(:find).with("37") { mock_award }
      mock_award.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the awards list" do
      Award.stub(:find) { mock_award }
      delete :destroy, :id => "1"
      response.should redirect_to(awards_url)
    end
  end

end
